Add fish deletion tests
dominpacek/testowanie1 pull request #4
Opened 2022-10-15 18:07 UTC by iruszpel

2022-10-15 22:08 UTC, sobczal2 requested changes
Z wielkim bólem serca, ale niestety muszę to Panu odbić. Informacje o zmianach o które proszę znajdują się w komentarzach.

2022-10-15 22:08 UTC, sobczal2 commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            var actual = await fishService.GetFishByIdAsync(fishInDb.Id);
Jest to rozwiązanie z pewnością działające, jednak sumienie nie pozwoli mi tego przepuścić. Uważam, że warto w testach unikać używania metod które nie są sprawdzane przez dany test dlatego sugerowałbym wykorzystać dbContextMock.Data.FirstOrDefault(x => x.Id == fishInDb.Id)

2022-10-15 22:08 UTC, sobczal2 commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Szansa na to, że test nie przejdzie przez to że trafi nam się dokładniem ten sam Guid jak w fishInDb jest równa 1 w 2^128 według wikipedii. Mimo tego, że szansa jest znikoma to zapewne zna Pan przypowieść dotyczącą wyborów w Belgii i myślę, że dla pewności warto tutaj zahardcodować Guida używając Guid.Parse()

2022-10-15 22:40 UTC, iruszpel commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Jest to absurdalne twierdzenie bowiem aplikacje na całym świecie opierają się na takim założeniu. Ogromne bazy danych dla systemów bankowych nie przejmują się takim przypadkiem, a ewentualne konsekwencje konfliktu mogą być ogromne. Cały sens użycia UUID opiera się na tym, że można nie sprawdzać konfliktów, a po prostu wygenerować nowy i z ogromnym prawdopodobieństwem będzie on inny niż pozostałe. Z tego powodu z przykrością uznaję Pana argument za inwalidę

2022-10-15 22:42 UTC, iruszpel commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            var actual = await fishService.GetFishByIdAsync(fishInDb.Id);
Niesamowita spostrzegawczość i piękna intuicja programistyczna, w pełni zgadzam się z Pańskim komentarzem

2022-10-15 22:49 UTC, iruszpel commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Niesamowity brak zrozumienia problemu szanowny Panie. Zupełnie inne podłoże problemu występowało w Belgijskich wyborach

2022-10-15 22:53 UTC, sobczal2 commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Jest to słuszna uwaga, prawdopodbnie jest to po prostu moja osobista preferencja. W takim wypadku decyzję pozostawię Panu, ale życzę także Panu absurdalnego pecha i oby Panu się ten test wyjebał. Pozdrawiam

2022-10-15 22:58 UTC, sobczal2 commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Proszę Pana, co do wyborów w Belgii planowałem tylko używając porównania zobrazować jak mała jest szansa na wystąpienie błędu w takiej sytuacji. Uważam, że porównanie jest poprawne, ponieważ podczas wyborów była bardzo mała szansa na to, że nastąpi bitflip, a jednak takie coś się wydarzyło. Uważam że zarówno wygenerowanie tego samego guida jak i bitflip są zdarzeniami losowymi, które po prostu miały szansę wystąpić. Jest mi bardzo przykro, jeżeli nie widzi Pan tak uderzającego podobieństwa.

2022-10-16 11:44 UTC, iruszpel commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Równie niewielka szansa jest na pożar podczas uruchamiania testów, czy nasza aplikacja również powinna być na to odporna? Idąc Pana logiką można rozpatrywać wszystkie niezwykle rzadko występujące losowe sytuacje

2022-10-16 12:11 UTC, sobczal2 commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Faktycznie pożar może i jest nawet bardziej prawdopodobny niż duplikacja Guidów aczkolwiek warto zauważyć, że przerobienie linijki kodu jest nieco prostsze i tańsze niż stawianie straży pożarnej w stan gotowości za każdym razem jak uruchamiamy testy

2022-10-16 12:13 UTC, sobczal2 commented on Testowanie1.Api.Test/Services/FishServiceTest.cs
> +            await Assert.ThrowsAsync<ApplicationNotFoundException>(() => fishService.DeleteFishAsync(Guid.NewGuid()));
Ale rozumiem Pański punkt widzenia i uszanuję Pańską decyzję, faktycznie z punktu widzenia działania testów nie ma to znaczenia, jest to moja prywatna preferencja.

2022-10-16 12:22 UTC, sobczal2 approved these changes
Solidnie napisane testy sprawdzające działanie naszego programu, dziękuję za wprowadzenie sugerowanej przeze mnie poprawki a także za dyskusję, która wiele mnie nauczyła.

2022-10-16 12:27 UTC, merged